language: python
python:
- "2.7"
before_install:
    - sudo apt-get install -y rng-tools
    - sudo rm -f /dev/random
    - sudo mknod -m 0666 /dev/random c 1 9
    - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
    - sudo /etc/init.d/rng-tools restart
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r test-requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors
before_script:
    - sudo /usr/sbin/rngd -r /dev/urandom
script:
    - coverage run --source pixelated setup.py test
after_success:
    - coveralls

